### ISSUE TITLE
Expose isImmutable method

### ISSUE THREAD

**Issue by aight8** [rtfeldman/seamless-immutable#191]

**Comment by aight8** [comment]
Why was with issue deleted without one comment?

**Comment by rtfeldman** [comment]
It was closed without comment because it was opened without a description. The title was "Expose isImmutable method," which is not much to go on considering the method is already exposed. I didn't want any contributors to waste their time trying to guess what you wanted, so I closed it.

I don't know what "Was using the method on the wrong immutable library" means, but I opened https://github.com/rtfeldman/seamless-immutable/issues/192 about the missing documentation. 🙂
