### ISSUE TITLE
Have banned methods return a new Immutable instance instead

### ISSUE THREAD

**Issue by dariocravero** [rtfeldman/seamless-immutable#22]
Hi,

I love the fact that this library is super small and that doesn't try to do anything else than making your data immutable :).

There's only one thing holding me back from using it though:

```
Immutable([3, 1, 4]).sort()
// This will throw an ImmutableError, because sort() is a mutating method.
```

Have you considered returning a new immutable structure with the sorted array instead? (the same applies for every other banned method).

Thanks :)
Darío

**Comment by rtfeldman** [comment]
I considered it, but the trouble is that doing this can mask bugs. For example:

```javascript
function foo() {
  var array = [3, 1, 4];

  array.sort()

  return array;
}
```

If you change that first line to be `Immutable([3, 1, 4])`, what should happen?

Currently `array.sort()` throws an exception, letting you know that some code that made sense with a mutable array no longer makes sense. If instead `array.sort()` just returns a sorted, immutable array, then now an unsorted array will be returned here, and you have a bug to track down - a potentially nasty one, if there is a lot of logic surrounding this code.

I prefer this API because you can take an immutable array and write any number of helper functions that return sorted ones, but the only way to make bugs like this easy to find is to override the mutable methods to throw an exception. :smiley:

**Comment by alanhogan** [comment]
Great explanation. Richard, you’re an A+ maintainer.

**Comment by dariocravero** [comment]
Thanks for the explanation. It makes sense :). So how are you going about those when you're using methods like `sort`? Are you doing something like this?

```
let array = Immutable([3, 1, 4])
array = Immutable(array.asMutable().sort())
```

**Comment by rtfeldman** [comment]
Thanks @alanhogan! :blush: 

@dariocravero Generally I'm using Underscore functions like [_.sortBy](http://underscorejs.org/#sortBy) and just calling `Immutable` on the result. No need to call `.asMutable()` in that case!

**Comment by dariocravero** [comment]
Good stuff :) Will give it a go then!

**Comment by tylercollier** [comment]
What about a development vs production flag for whether an error should be thrown? I am appreciative of the thrown error as I change from ImmutableJS to this library. But after the transition, my code is cluttered using `_.sortBy()` instead of the built-in `sort()`.

While the workaround is not terrible, I thought I'd voice my opinion so others who find this issue know there's at least 1 other person wishing for it!

**Comment by rtfeldman** [comment]
@tylercollier Good news! :smile_cat: https://github.com/rtfeldman/seamless-immutable#performance

**Comment by tylercollier** [comment]
Thanks for the link to that section of the doc, which I read (and admit to not reading before, but you already had me sold on performance from your blog post :-) I think you saw my original comment, which was phrased as an option that I might toggle one way in dev and another in production, but I rephrased it because that's not what I'm really after. What I'd like is an option I can set. My concern here is convenience for me as a developer rather than performance. I'm guessing you have a build step that pulls those checks out when you create a minified production build, rather than an option I can set?

**Comment by rtfeldman** [comment]
Ahh got it, yeah that's correct. Sorry for the confusion!

That said, I'd honestly rather not add that complication to dev mode. :x

**Comment by nin-jin** [comment]
You can add method sorted(fn) that returns sorted copy of array.

**Comment by Nickman87** [comment]
I like the idea of introducing additional methods to support the same functionality as original mutation methods, but have them return an immutable result instead as @nin-jin suggested.
Maybe even more obvious like `sort_immutable()` so you should know what to expect from it?
This would remove the need for custom functions doing the same thing but requiring an additional dependency in your code.
