### ISSUE TITLE
Question: How does this compare to icepick?

### ISSUE THREAD

**Issue by jakubholynet** [rtfeldman/seamless-immutable#38]
Hello,

I wonder whether I should pick [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) or [icepick](https://github.com/aearly/icepick). They both seem to be doing the same thing, providing utilities for "modifying" deeply frozen data structures. I can see some differences but know too little to be able to really compare them and decide. Could you be so kind and describe the advantages of seamless over icepick and vice versa? Thanks a lot!

PS: I'll ask at the other project as well

**Comment by rtfeldman** [comment]
From reading icepick's description, it looks like they are both doing the same thing at a high level: providing immutable data structures that are backwards-compatible with vanilla JS arrays and objects, and which intelligently do shallow rather than deep cloning because shallow yields equivalent results for immutable data structures. 

It looks like the differences are:

- seamless-immutable has higher test coverage
- seamless-immutable has an optional production build that doesn't actually freeze the objects, which runs faster
- each library has its own set of convenience methods

**Comment by jakubholynet** [comment]
Thanks a lot! Perhaps it would be useful to add this to the README?

**Comment by rtfeldman** [comment]
I'd rather keep the README focused, but now it's easy enough to link someone with the same question to this discussion! :smile:
