### ISSUE TITLE
Internet Explorer 8 compatibility?

### ISSUE THREAD

**Issue by jimbolla** [rtfeldman/seamless-immutable#60]
I noticed the compatibility list has IE9 and up, but does not list IE8. Unfortunately we have to support that. Has anyone actually tested `seamless-immutable` in IE8?

**Comment by rtfeldman** [comment]
The development build definitely cannot work in IE8 because IE8 does not support Object.freeze. I can't think of any reason why the production build would not work, however.

I don't personally have the bandwidth to test this, but if someone else can verify this, I can update the README to note that the production build works in IE8.

**Comment by lewisje** [comment]
The worse problem with IE8 is that `Object.defineProperty` only works on DOM nodes, and even a polyfill won't give IE8 the ability to make ordinary object members non-writable and non-deletable.

**Comment by rtfeldman** [comment]
Thanks @lewisje - sounds like the resolution here is that it can't work.
