### ISSUE TITLE
Add `.merge`, `.without` etc as static methods

### ISSUE THREAD

**Issue by plestik** [rtfeldman/seamless-immutable#81]
Is it possibly a good idea to add `.merge`, `.omit`, `.without`, `.asMutable()` to seamless-immutable as static methods? This way, in production, no properties or methods have to be added to an object. Also, it reduces the chance of trying to call one of those methods on an object which is not wrapped.

**Comment by rtfeldman** [comment]
I like this idea, and I wish I'd thought of it back when I first made the library! (A production-specific build was not on the radar back then.)

At this point, though, this would be a monumental breaking change for the sake of a performance improvement it's not clear would make a difference for people using the library today.

This seems unlikely to be the right move in the foreseeable future, so I'm going to close this rather than leave it in limbo. Great thought, though!
