### ISSUE TITLE
process.env.NODE_ENV unavailable in browser

### ISSUE THREAD

**Issue by ryanfields** [rtfeldman/seamless-immutable#88]
When attempting to use this package in a browser, I run into the error of ```process``` being undefined when it's called from the ```makeImmutable``` function.  It seems like there should be a check for whether or not process exists before checking the env, since it won't exist in a browser.  This would also mean having an alternate means of putting seamless-immutable into production mode when running in a browser.

**Comment by bholloway** [comment]
+1

**Comment by rtfeldman** [comment]
Hi @ryanfields and @bholloway,

You want to use either the [development build](https://github.com/rtfeldman/seamless-immutable/blob/5.0.1/seamless-immutable.development.js) or the [production build](https://github.com/rtfeldman/seamless-immutable/blob/5.0.1/seamless-immutable.production.min.js) - the source build, which has `process` in it, should not be used in the browser.

Sorry if that was unclear! :smile:

**Comment by bholloway** [comment]
Thanks @ryanfields. I was using in JSBin so that should solve my issue.

However there might be a problem in the `bower.json` in that case, since it points to the `src` file. I would say it 99% of cases a Bower package goes straight to Web, rather than being used/built in a Node-like environment.

I am happy give you a PR for that fix and some clarification in the Docs but if you are opposed, or it is quicker for you to change yourself, then just let me know.

**Comment by rtfeldman** [comment]
A PR would be great!
